spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    #url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 123456
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: none
    #properties:
     # hibernate:
        #dialect: org.hibernate.dialect.H2Dialect
        #dialect: org.hibernate.dialect.MySQL8Dialect
        #format_sql: true
        #id:
        #  new_generator_mappings: false

server:
   port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: 12345abcdefghijkl
      expire-length: 600000 # 10 minutes duration by default: 10 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data